// Generated by scripts/generate_reference.py; do not edit manually.
export const apiModuleIndex = [
  {
    "module": "fs_diloco",
    "route": "/reference/fs_diloco",
    "summary": "定义基于共享文件系统的 Decoupled DiLoCo Python 包。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.core",
    "route": "/reference/fs_diloco/core",
    "summary": "集中提供配置、源码身份、运行描述符和制品版本契约。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.core.adoption_rules",
    "route": "/reference/fs_diloco/core/adoption_rules",
    "summary": "为配置加载和运行期全局版本采纳策略提供不依赖 Torch 的校验。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 0,
      "functions": 1,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.core.config",
    "route": "/reference/fs_diloco/core/config",
    "summary": "定义 Full Protocol 的严格配置模型、加载、解析和跨字段校验。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 18,
      "functions": 17,
      "methods": 3
    }
  },
  {
    "module": "fs_diloco.core.constants",
    "route": "/reference/fs_diloco/core/constants",
    "summary": "保存文件系统 DiLoCo 原型跨模块共享的常量。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.core.run_descriptor",
    "route": "/reference/fs_diloco/core/run_descriptor",
    "summary": "读取并验证不可变运行描述符、源码身份和配置身份。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 2,
      "functions": 6,
      "methods": 1
    }
  },
  {
    "module": "fs_diloco.core.source_identity",
    "route": "/reference/fs_diloco/core/source_identity",
    "summary": "计算运行源码范围、Git 状态和内容指纹。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 0,
      "functions": 5,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.core.versions",
    "route": "/reference/fs_diloco/core/versions",
    "summary": "定义可独立演进的 Full Protocol 制品版本号。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.core",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.learner",
    "route": "/reference/fs_diloco/learner",
    "summary": "提供强制 fenced Learner 运行时的公开、无 Torch 启动入口。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.modeling",
    "route": "/reference/fs_diloco/modeling",
    "summary": "集中提供模型、数据集、参数索引和优化器实现。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.modeling.hf_data",
    "route": "/reference/fs_diloco/modeling/hf_data",
    "summary": "加载训练数据并构造可恢复的无限批次迭代器。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 1,
      "functions": 7,
      "methods": 1
    }
  },
  {
    "module": "fs_diloco.modeling.hf_identity",
    "route": "/reference/fs_diloco/modeling/hf_identity",
    "summary": "拒绝不满足不可变身份要求的 Hugging Face 本地引用。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 0,
      "functions": 1,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.modeling.hf_model",
    "route": "/reference/fs_diloco/modeling/hf_model",
    "summary": "构造 Hugging Face 因果语言模型和合成冒烟测试模型。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 3,
      "functions": 4,
      "methods": 3
    }
  },
  {
    "module": "fs_diloco.modeling.outer_optim",
    "route": "/reference/fs_diloco/modeling/outer_optim",
    "summary": "对扁平全局参数执行显式外层优化器更新。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 0,
      "functions": 4,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.modeling.param_index",
    "route": "/reference/fs_diloco/modeling/param_index",
    "summary": "建立确定性的可训练参数索引，并在模型参数与扁平向量之间转换。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 0,
      "functions": 11,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.modeling.training",
    "route": "/reference/fs_diloco/modeling/training",
    "summary": "构造 Full Protocol Learner 使用的内层优化器和学习率调度器。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.modeling",
    "counts": {
      "classes": 0,
      "functions": 3,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.observability",
    "route": "/reference/fs_diloco/observability",
    "summary": "提供结构化进程日志和不可变 Actor 遥测。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.observability",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.observability.logging_utils",
    "route": "/reference/fs_diloco/observability/logging_utils",
    "summary": "将进程事件、异常和运行证明写入 JSONL。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.observability",
    "counts": {
      "classes": 2,
      "functions": 1,
      "methods": 5
    }
  },
  {
    "module": "fs_diloco.protocol",
    "route": "/reference/fs_diloco/protocol",
    "summary": "定义不依赖运行时和存储实现的 Full Protocol 值对象。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.protocol._validation",
    "route": "/reference/fs_diloco/protocol/_validation",
    "summary": "提供协议边界使用的严格、无外部依赖校验原语。",
    "isPackage": false,
    "visibility": "internal",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 0,
      "functions": 10,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.protocol.authority",
    "route": "/reference/fs_diloco/protocol/authority",
    "summary": "定义跨越 authority 边界的类型化应用对象。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 15,
      "functions": 0,
      "methods": 14
    }
  },
  {
    "module": "fs_diloco.protocol.contributor",
    "route": "/reference/fs_diloco/protocol/contributor",
    "summary": "定义唯一的 contributor fence 和固定 stream-pool membership scope。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 2,
      "functions": 0,
      "methods": 5
    }
  },
  {
    "module": "fs_diloco.protocol.cycle_receipt",
    "route": "/reference/fs_diloco/protocol/cycle_receipt",
    "summary": "定义 CycleReceiptV1 的严格序列化边界。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 1,
      "functions": 3,
      "methods": 6
    }
  },
  {
    "module": "fs_diloco.protocol.data_cursor",
    "route": "/reference/fs_diloco/protocol/data_cursor",
    "summary": "定义索引化或物化训练数据的确定性游标和恢复状态。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 2,
      "functions": 0,
      "methods": 5
    }
  },
  {
    "module": "fs_diloco.protocol.merge",
    "route": "/reference/fs_diloco/protocol/merge",
    "summary": "计算 proposal 的 token/陈旧度权重并执行张量加权平均。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 0,
      "functions": 4,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.protocol.proposal",
    "route": "/reference/fs_diloco/protocol/proposal",
    "summary": "定义 FullUpdateProposalV2 的严格序列化边界。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 1,
      "functions": 2,
      "methods": 6
    }
  },
  {
    "module": "fs_diloco.protocol.scheduler",
    "route": "/reference/fs_diloco/protocol/scheduler",
    "summary": "定义 scheduler uncertainty 状态和 operator request 边界。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 3,
      "functions": 1,
      "methods": 5
    }
  },
  {
    "module": "fs_diloco.protocol.selection",
    "route": "/reference/fs_diloco/protocol/selection",
    "summary": "按持久服务历史确定性选择 contributor。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 1,
      "functions": 0,
      "methods": 2
    }
  },
  {
    "module": "fs_diloco.protocol.token_accounting",
    "route": "/reference/fs_diloco/protocol/token_accounting",
    "summary": "执行 Learner segment 与 authority token 的确定性记账。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.protocol",
    "counts": {
      "classes": 3,
      "functions": 1,
      "methods": 11
    }
  },
  {
    "module": "fs_diloco.runtime",
    "route": "/reference/fs_diloco/runtime",
    "summary": "组合 Learner 与 Syncer 进程运行时。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.runtime.adoption",
    "route": "/reference/fs_diloco/runtime/adoption",
    "summary": "实现 Full Learner 的全局版本采纳状态机。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 10,
      "functions": 3,
      "methods": 44
    }
  },
  {
    "module": "fs_diloco.runtime.learner",
    "route": "/reference/fs_diloco/runtime/learner",
    "summary": "执行通过 admission 后的 Full Protocol 本地训练循环。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 0,
      "functions": 4,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.runtime.learner_control",
    "route": "/reference/fs_diloco/runtime/learner_control",
    "summary": "在不导入 Torch 的阶段决定 Learner 循环控制行为。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 0,
      "functions": 2,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.runtime.learner_entrypoint",
    "route": "/reference/fs_diloco/runtime/learner_entrypoint",
    "summary": "执行 Full Protocol Learner 的无 Torch admission 入口。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 0,
      "functions": 2,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.runtime.pbs_scheduler",
    "route": "/reference/fs_diloco/runtime/pbs_scheduler",
    "summary": "查询和提交容量控制使用的 PBS 作业。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 2,
      "functions": 6,
      "methods": 5
    }
  },
  {
    "module": "fs_diloco.runtime.services",
    "route": "/reference/fs_diloco/runtime/services",
    "summary": "汇集 Full Protocol 运行时组合的窄职责有状态服务。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.runtime.services",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.runtime.services.dynamic_capacity",
    "route": "/reference/fs_diloco/runtime/services/dynamic_capacity",
    "summary": "持久化 capacity 观测并与 PBS launch 状态对账。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime.services",
    "counts": {
      "classes": 3,
      "functions": 0,
      "methods": 19
    }
  },
  {
    "module": "fs_diloco.runtime.services.maintenance",
    "route": "/reference/fs_diloco/runtime/services/maintenance",
    "summary": "执行带 fence 的在线归档、压缩和身份校验制品清理。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime.services",
    "counts": {
      "classes": 1,
      "functions": 1,
      "methods": 2
    }
  },
  {
    "module": "fs_diloco.runtime.services.merge",
    "route": "/reference/fs_diloco/runtime/services/merge",
    "summary": "为正常路径与终态路径提供唯一的合并和发布实现。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime.services",
    "counts": {
      "classes": 2,
      "functions": 0,
      "methods": 2
    }
  },
  {
    "module": "fs_diloco.runtime.services.terminal",
    "route": "/reference/fs_diloco/runtime/services/terminal",
    "summary": "执行 Full Protocol 的关闭、drain 和受限最终合并。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime.services",
    "counts": {
      "classes": 1,
      "functions": 2,
      "methods": 6
    }
  },
  {
    "module": "fs_diloco.runtime.syncer",
    "route": "/reference/fs_diloco/runtime/syncer",
    "summary": "组合 fenced Syncer 的服务、合并循环和终态流程。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 1,
      "functions": 11,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.runtime.syncer_entrypoint",
    "route": "/reference/fs_diloco/runtime/syncer_entrypoint",
    "summary": "验证候选身份、获取 leader lease 并启动 Syncer。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.runtime",
    "counts": {
      "classes": 1,
      "functions": 5,
      "methods": 6
    }
  },
  {
    "module": "fs_diloco.storage",
    "route": "/reference/fs_diloco/storage",
    "summary": "汇集 Full Protocol 的持久化适配器。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.admission",
    "route": "/reference/fs_diloco/storage/admission",
    "summary": "在 Learner 导入 Torch 前提供文件系统 admission 请求和响应边界。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 4,
      "functions": 30,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.artifact_policy",
    "route": "/reference/fs_diloco/storage/artifact_policy",
    "summary": "分类版本化运行制品并限制通用清理范围。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 2,
      "functions": 5,
      "methods": 3
    }
  },
  {
    "module": "fs_diloco.storage.atomic_io",
    "route": "/reference/fs_diloco/storage/atomic_io",
    "summary": "提供原子写入、不可变发布和安全读取的文件系统原语。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 1,
      "functions": 14,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.audit_archive",
    "route": "/reference/fs_diloco/storage/audit_archive",
    "summary": "发布不可变 authority 审计批次并执行离线去重。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 0,
      "functions": 19,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.authority",
    "route": "/reference/fs_diloco/storage/authority",
    "summary": "初始化 SQLite authority，并提供类型化读取与显式 fenced command。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 11,
      "functions": 20,
      "methods": 108
    }
  },
  {
    "module": "fs_diloco.storage.control",
    "route": "/reference/fs_diloco/storage/control",
    "summary": "发布 epoch-scoped 控制对象；固定路径只作为可修复缓存。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 3,
      "functions": 17,
      "methods": 7
    }
  },
  {
    "module": "fs_diloco.storage.leader_lease",
    "route": "/reference/fs_diloco/storage/leader_lease",
    "summary": "定义 leader lease 值对象和本地单调时钟安全边界。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 5,
      "functions": 0,
      "methods": 6
    }
  },
  {
    "module": "fs_diloco.storage.object_store",
    "route": "/reference/fs_diloco/storage/object_store",
    "summary": "按内容身份读取不可变 payload 对象。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 3,
      "functions": 6,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.paths",
    "route": "/reference/fs_diloco/storage/paths",
    "summary": "集中构造运行根目录中的规范路径。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 1,
      "functions": 2,
      "methods": 54
    }
  },
  {
    "module": "fs_diloco.storage.run_initializer",
    "route": "/reference/fs_diloco/storage/run_initializer",
    "summary": "以 crash-recoverable、no-replace 方式发布新的共享文件系统运行根目录。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 0,
      "functions": 29,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.tensor_codec",
    "route": "/reference/fs_diloco/storage/tensor_codec",
    "summary": "使用 Safetensors 编码和读取全局权重、更新向量与外层优化器状态。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 0,
      "functions": 13,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.tensor_identity",
    "route": "/reference/fs_diloco/storage/tensor_identity",
    "summary": "提供不依赖存储和建模层的底层张量身份计算。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 0,
      "functions": 1,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.storage.terminal_request",
    "route": "/reference/fs_diloco/storage/terminal_request",
    "summary": "发布和读取 operator 发起的不可变终态关闭请求。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.storage",
    "counts": {
      "classes": 0,
      "functions": 2,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.syncer",
    "route": "/reference/fs_diloco/syncer",
    "summary": "提供强制 fenced Syncer candidate 运行时的公开入口。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.tools",
    "route": "/reference/fs_diloco/tools",
    "summary": "汇集运行初始化、检查、operator request 和清理工具。",
    "isPackage": true,
    "visibility": "public",
    "package": "fs_diloco.tools",
    "counts": {
      "classes": 0,
      "functions": 0,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.tools.analysis",
    "route": "/reference/fs_diloco/tools/analysis",
    "summary": "通过 durable authority 检查一个当前 Full Protocol 运行。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.tools",
    "counts": {
      "classes": 0,
      "functions": 6,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.tools.init_run",
    "route": "/reference/fs_diloco/tools/init_run",
    "summary": "在提交 PBS Actor 前初始化不可变 Full Protocol 运行。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.tools",
    "counts": {
      "classes": 0,
      "functions": 5,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.tools.launch_independent_run",
    "route": "/reference/fs_diloco/tools/launch_independent_run",
    "summary": "初始化运行并提交相互独立的 Full Protocol PBS Actor。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.tools",
    "counts": {
      "classes": 0,
      "functions": 6,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.tools.request_terminal_close",
    "route": "/reference/fs_diloco/tools/request_terminal_close",
    "summary": "为 Full Protocol 运行发布一份不可变 manual-close request。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.tools",
    "counts": {
      "classes": 0,
      "functions": 1,
      "methods": 0
    }
  },
  {
    "module": "fs_diloco.tools.resolve_scheduler_uncertainty",
    "route": "/reference/fs_diloco/tools/resolve_scheduler_uncertainty",
    "summary": "创建用于解决 scheduler uncertainty 的不可变 operator request。",
    "isPackage": false,
    "visibility": "public",
    "package": "fs_diloco.tools",
    "counts": {
      "classes": 0,
      "functions": 3,
      "methods": 0
    }
  }
] as const;

export const apiReferenceStats = {
  "modules": 63,
  "packages": 9,
  "classes": 105,
  "functions": 296,
  "methods": 329,
  "fields": 560,
  "variables": 51,
  "symbols": 1341
} as const;
