"""Version numbers for independently versioned Full Protocol artifacts.

Do not replace these constants with one generic format version.  Each value is
owned by a producer/consumer boundary and may advance independently.
"""

PROTOCOL_VERSION = 5
AUTHORITY_SCHEMA_VERSION = 12
CONFIG_SCHEMA_VERSION = 2
PROPOSAL_FORMAT_VERSION = 3
PROPOSAL_POINTER_FORMAT_VERSION = 3
CYCLE_RECEIPT_FORMAT_VERSION = 2
LEARNER_HEARTBEAT_FORMAT_VERSION = 2
SYNCER_HEARTBEAT_FORMAT_VERSION = 2
CONTROL_FORMAT_VERSION = 3
RUN_DESCRIPTOR_FORMAT_VERSION = 3
RUN_IDENTITY_FORMAT_VERSION = 2
SOURCE_MANIFEST_FORMAT_VERSION = 2
ACTOR_ATTESTATION_FORMAT_VERSION = 1
ARTIFACT_POLICY_FORMAT_VERSION = 1
PARAM_INDEX_FORMAT_VERSION = 1
