"""Version numbers for independently versioned Full Protocol v4 artifacts.

Do not replace these constants with one generic format version.  Each value is
owned by a producer/consumer boundary and may advance independently.
"""

PROTOCOL_VERSION = 4
AUTHORITY_SCHEMA_VERSION = 7
CONFIG_SCHEMA_VERSION = 1
PROPOSAL_FORMAT_VERSION = 2
PROPOSAL_POINTER_FORMAT_VERSION = 2
CYCLE_RECEIPT_FORMAT_VERSION = 1
PROGRESS_POINTER_FORMAT_VERSION = 1
LEARNER_HEARTBEAT_FORMAT_VERSION = 2
SYNCER_HEARTBEAT_FORMAT_VERSION = 2
CONTROL_FORMAT_VERSION = 2
MEMBERSHIP_FORMAT_VERSION = 2
LAUNCH_RECORD_FORMAT_VERSION = 2
RUN_DESCRIPTOR_FORMAT_VERSION = 2
SOURCE_MANIFEST_FORMAT_VERSION = 2
ACTOR_ATTESTATION_FORMAT_VERSION = 1
ARTIFACT_POLICY_FORMAT_VERSION = 1
PARAM_INDEX_FORMAT_VERSION = 1
